export const GET_COIN_DETAILS_SUCCESS = "GET_COIN_DETAILS_SUCCESS";
export const GET_COIN_DETAILS_FAILED = "GET_COIN_DETAILS_FAILED";
export const GET_TRADE_VOLUME_SUCCESS = "GET_TRADE_VOLUME_SUCCESS";
export const GET_TRADE_VOLUME_FAILED = "GET_TRADE_VOLUME_FAILED";
export const TOGGLE_FAVOURITE = "TOGGLE_FAVOURITE";
export const SORT_PRICE = "SORT_PRICE";
export const SORT_VOLUME = "SORT_VOLUME";